//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public string TextId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string PostedDate { get; set; }
        public string LeadText { get; set; }
        public string BodyText { get; set; }
        public string ImageUrl { get; set; }
        public string OriginalUrl { get; set; }
    }
}
